services:
  db:
    container_name: postgres_test
    image: postgres:15.1
    environment:
      POSTGRES_USER: kamil
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  kgarbacki-api:
    container_name: kgarbacki-api
    image: kamilgarbacki/kgarbacki-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_test:5432/customer
    ports:
      - "8088:8080"
    networks:
      - postgres
    depends_on:
      - db
    restart: unless-stopped

  kgarbacki-react:
    container_name: kgarbacki-react
    image: kamilgarbacki/kgarbacki-react
    build:
      context: frontend/react
      args:
        api_base_url: http://localhost:8088
    ports:
      - "3000:5173"
    depends_on:
      - kgarbacki-api
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: